<?xml version="1.0" encoding="utf-8"?><Database Name="OnlineTest" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\OnlineTest.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OnlineTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.username" Member="usernames">
    <Type Name="username">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Member="username1" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="privilage" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.test" Member="tests">
    <Type Name="test">
      <Column Name="testID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timeStart" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="timeEnd" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="totalMarks" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="subjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="test_testquestion" Member="testquestions" ThisKey="testID" OtherKey="testID" Type="testquestion" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.subject" Member="subjects">
    <Type Name="subject">
      <Column Name="subjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="subjectCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.teacher" Member="teachers">
    <Type Name="teacher">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="classID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.question" Member="questions">
    <Type Name="question">
      <Column Name="questionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="questionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="questionText" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="questionAnswer" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="questionMarks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="question_objectiveanswer" Member="objectiveanswers" ThisKey="questionID" OtherKey="questionID" Type="objectiveanswer" Cardinality="One" />
      <Association Name="testquestion_question" Member="testquestion" ThisKey="questionID" OtherKey="questionID" Type="testquestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.testquestion" Member="testquestions">
    <Type Name="testquestion">
      <Column Name="testID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="questionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="testquestion_question" Member="questions" ThisKey="questionID" OtherKey="questionID" Type="question" Cardinality="One" />
      <Association Name="test_testquestion" Member="test" ThisKey="testID" OtherKey="testID" Type="test" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.objectiveanswers" Member="objectiveanswers">
    <Type Name="objectiveanswer">
      <Column Name="questionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerA" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="AnswerB" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="AnswerC" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="AnswerD" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="question_objectiveanswer" Member="question" ThisKey="questionID" OtherKey="questionID" Type="question" IsForeignKey="true" />
    </Type>
  </Table>
</Database>